{
 "title": "Example dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "3s",
 "panels": [
  {
   "title": "Requests per second",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_count{status=\"200\"}",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_count{status!=\"200\"}",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "flask_http_request_created{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average response time [30s]",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_sum{status=\"200\"}",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 10, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"example\"}",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "process_cpu_seconds_total{}", "legendFormat": "cpu" }
   ]
  }
 ]
}