apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: https://github.com/maximilianoPizarro/prometheus_flask_exporter
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: app
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: app
    app.kubernetes.io/name: app
    app.kubernetes.io/part-of: app-flask
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.9-ubi8
  name: app
spec:
  lookupPolicy:
    local: false
