apiVersion: v1
data:
  WebHookSecretKey: NjQ2NWI1NDBjNzJlMGFkMw==
kind: Secret
metadata:
  labels:
    app: app
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: app
    app.kubernetes.io/name: app
    app.kubernetes.io/part-of: app-flask
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.9-ubi8
  name: app-github-webhook-secret
type: Opaque
