apiVersion: v1
imagePullSecrets:
- name: prometheus-prometheus-node-exporter-dockercfg-pcldd
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: mpizarro-dev
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: app-flask
    app.kubernetes.io/name: prometheus-node-exporter
    app.kubernetes.io/part-of: app-flask-node-exporter
    app.kubernetes.io/version: 1.7.0
    helm.sh/chart: prometheus-node-exporter-4.30.3
  name: prometheus-prometheus-node-exporter
secrets:
- name: prometheus-prometheus-node-exporter-dockercfg-pcldd
