apiVersion: v1
imagePullSecrets:
- name: prometheus-server-dockercfg-8wf4z
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: mpizarro-dev
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: app-flask
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: app-flask
    app.kubernetes.io/version: v2.50.1
    helm.sh/chart: prometheus-25.17.0
  name: prometheus-server
secrets:
- name: prometheus-server-dockercfg-8wf4z
