apiVersion: v1
automountServiceAccountToken: false
imagePullSecrets:
- name: grafana-dockercfg-sxvtn
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: grafana
    meta.helm.sh/release-namespace: mpizarro-dev
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 10.4.0
    helm.sh/chart: grafana-7.3.7
  name: grafana
secrets:
- name: grafana-dockercfg-sxvtn
